### ISSUE TITLE
Duplicate files in JDK and BIN packages

### ISSUE THREAD

**Issue by mariodebian** [rraptorr/oracle-java7#22] opened 2015-01-29 10:00 UTC
In last version (7.76) there are duplicate files in jdk and bin packages and because of this I can't install oracle-java7-jdk.

```
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/ControlPanel
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/java
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/javaws
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/jcontrol
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/keytool
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/orbd
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/pack200
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/policytool
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/rmid
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/rmiregistry
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/servertool
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/tnameserv
      2 ./usr/lib/jvm/java-7-oracle-1.7.0.76/bin/unpack200
```

Files in x.x.x/bin dir in JDK and also in BIN packages

In oracle-java8 there is no duplication

**Comment by rraptorr** [comment] 2015-01-29 10:32
I have no idea how you managed to get such results, but I've double checked and there is no such duplication and the packages install and work fine (and I'm using them on a few hundred servers).

Unless you provide more detailed information I cannot help.

**Comment by rraptorr** [comment] 2015-02-02 11:09
Closing as I cannot reproduce this and the reporter is not interested in the issue.

**Closed by rraptorr** 2015-02-02 11:09 UTC

**Comment by mariodebian** [comment] 2015-02-02 15:42
Sorry for the noise, It was a not clean build of oracle-java7.

I can't reproduce too

Sorry again
